### PR TITLE
feat(ruby): adding ruby project

### PR DESCRIPTION
**Pull request by cherryramatisdev**
If any improvement is necessary for this PR to be merged, please let me know!

> Thanks to @DanielHe4rt for inspiring me to contribute on this repository.

### CODE REVIEW

**Review by DanielHe4rt — APPROVED** [review]

**Comment by DanielHe4rt** [comment]
@annastuchlik @tzach I think that's everything good to go.

Maybe a last review just in case :p

also @cherryramatisdev thanks for the awesome contribution!

**Comment by DanielHe4rt** [comment]
Hey @cherryramatisdev I think that we're good to go on this PR. Could you please validate if there's anything missing and rebase your branch?

Thanks!

**Comment by cherryramatisdev** [comment]
I was reviewed a couple times and it's all good with the code propose! I did the rebase as you mentioned @DanielHe4rt 

Thanks again

**Review by DanielHe4rt — APPROVED** [review]
LGTM!

**Pull request merged**
